apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
data:
  jaeger-conf.yaml: |-
    service:
      extensions: [jaeger_storage, jaeger_query, healthcheckv2]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger_storage_exporter]
      telemetry:
        resource:
          service.name: jaeger
        metrics:
          level: detailed
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888

    extensions:
      healthcheckv2:
        use_v2: true
        http:

      jaeger_query:
        storage:
          traces: some_store
          traces_archive: another_store
        ui:
          config_file: /jaeger/etc/config-ui.json
          log_access: true

          
      jaeger_storage:
        backends:
          some_store:
            badger:
              directories:
                keys: "/tmp/jaeger/"
                values: "/tmp/jaeger/"
              ephemeral: false
          another_store:
            badger:
              directories:
                keys: "/tmp/jaeger_archive/"
                values: "/tmp/jaeger_archive/"
              ephemeral: false


    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch:
     

    exporters:
      jaeger_storage_exporter:
        trace_storage: some_store


  config-ui.json: |-
    {
      "archiveEnabled": true
    }