apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jaeger.name }}-deployment
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: load
                    operator: In
                    values:
                      - "true"
      containers:
      - name: jaeger
        image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
        imagePullPolicy: {{ .Values.jaeger.image.pullPolicy }}
        ports:
        - name: ui
          containerPort: {{ .Values.jaeger.uiService.targetPort }}
        - name: otlp
          containerPort: {{ .Values.jaeger.internalService.targetPort }}
