apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    ###############################################################################
    # 1) SOURCE – tail only the flask-server container logs in the default ns
    ###############################################################################
    <source>
      @type tail
      path /var/log/containers/*_default_flask-server-istio-*.log
      pos_file /fluentd/pos/flask-server-istio.pos
      tag  otlp.span
      read_from_head true
      <parse>
        @type cri
      </parse>
    </source>


    <filter otlp.span>
      @type grep
      <regexp>
        key stream
        pattern /^stdout$/
      </regexp>
      <regexp>
        key message
        pattern /^\{/
      </regexp>
    </filter>

    ###############################################################################
    # 2) FILTER – lift the JSON span string into `body`
    ###############################################################################
    <filter otlp.span>
      @type record_transformer
      enable_ruby true
      <record>
        body ${record["message"]}   
      </record>
      remove_keys message stream time tag
    </filter>

    ###############################################################################
    # 3) OUTPUT – POST one span JSON per request to Jaeger OTLP/HTTP
    ###############################################################################
    <match otlp.span>
      @type http
      endpoint http://jaeger-http-service.default.svc.cluster.local:4318/v1/traces
      http_method post
      content_type application/json 

      <format>
        @type single_value
        message_key body
        add_newline false
      </format>

      <buffer>
        flush_interval 1s
      </buffer>
    </match>

    <match otlp.span>
      @type stdout
      @log_level debug
    </match>