apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.otelCollector.name }}-service
  labels:
    app: otel-collector
spec:
  type: {{ .Values.otelCollector.service.type }}
  ports:
  - name: otlp
    port: {{ .Values.otelCollector.service.port }}
    targetPort: {{ .Values.otelCollector.service.targetPort }}
  selector:
    app: otel-collector