apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.otelCollector.config.name }}-config
data:
  collector.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"

    processors:
      batch:
        timeout: 1s  
        send_batch_size: 50 
      
    exporters:
      otlp/jaeger:
        endpoint: "{{ .Values.jaeger.internalService.name }}-service:{{ .Values.jaeger.internalService.targetPort }}"
        tls:
          insecure: true
      file:
        path: "/traces/trace_output.json"
        format: json

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/jaeger, file]