apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.uiService.name }}-service
  labels:
    app: jaeger
spec:
  type: {{ .Values.jaeger.uiService.type }}
  ports:
  - name: ui
    port: {{ .Values.jaeger.uiService.port }}
    targetPort: {{ .Values.jaeger.uiService.targetPort }}
    nodePort: {{ .Values.jaeger.uiService.nodePort }}
  selector:
    app: jaeger
