apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-server
  labels:
    app: flask-server
spec:
  type: {{ .Values.server.service.type }}
  ports:
  - name: http
    port: {{ .Values.server.service.port }}
    targetPort: {{ .Values.server.service.port }}
    protocol: TCP
  selector:
    app: flask-server
