apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jaeger.internalService.name }}-service
  labels:
    app: jaeger
spec:
  type: {{ .Values.jaeger.internalService.type }}
  ports:
  - name: otlp
    port: {{ .Values.jaeger.internalService.port }}
    targetPort: {{ .Values.jaeger.internalService.targetPort }}
  selector:
    app: jaeger
