apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.jaeger.name }}-deployment
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: load
                    operator: In
                    values:
                      - "true"

      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
          - containerPort: 16686  # Jaeger UI
          - containerPort: 14250  
          - containerPort: 14268  # Collector HTTP
          - containerPort: 9411   # Zipkin
          - containerPort: 4317