apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-client
  labels:
    app: flask-client
spec:
  type: {{ .Values.client.service.type }}
  ports:
  - name: http
    port: {{ .Values.client.service.port }}
    targetPort: {{ .Values.client.service.port }}
    protocol: TCP
  selector:
    app: flask-client
