apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
data:
  loadtest.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export const options = {
      stages: [
        { duration: '0.5m', target: 25 }, // ramp-up
        { duration: '2m', target: 25 }, // sustain
        { duration: '0.5m', target: 0 },  // ramp-down
      ],
      thresholds: {
        http_req_failed: ['rate<0.01'],
        http_req_duration: ['p(95)<500'], 
      },
    };

    const BASE_URL = 'http://release2-flask-client-istio.default.svc.cluster.local:8001/echo';
    const PARAMS = { headers: { 'Content-Type': 'application/json' }, timeout: '3s' };

    export default function () {
      const res = http.post(
        BASE_URL,
        JSON.stringify({ message: 'Latency test' }),
        PARAMS,
      );

      check(res, { 'status 200': (r) => r.status === 200 });
      sleep(Math.random() * 0.5);    
    }
